import {
  LayoutDashboard,
  Package,
  Factory,
  Warehouse,
  ShoppingCart,
  Building2,
  DollarSign,
  Calculator,
  FileSpreadsheet,
  AlertTriangle,
  ShieldCheck,
  Users,
  Settings,
  UserCog,
  Shield,
  Activity,
  Coins,
  Scale
} from "lucide-react";
import type { MenuItem } from "./types";

export const menuItems: MenuItem[] = [
  {
    id: "dashboard",
    name: "Dashboard",
    icon: <LayoutDashboard size={18} />,
    submenu: [
      {
        id: "dashboard-sales",
        name: "Sales",
        href: "/dashboard/sales",
        icon: <LayoutDashboard size={16} />,
        module: "dashboard_sales",
      },
      {
        id: "dashboard-accounting",
        name: "Accounting",
        href: "/dashboard/accounting",
        icon: <Calculator size={16} />,
        module: "dashboard_accounting",
      },
      {
        id: "dashboard-hrd",
        name: "HRD",
        href: "/dashboard/hrd",
        icon: <Users size={16} />,
        module: "dashboard_hrd",
      },
      {
        id: "dashboard-finance",
        name: "Finance",
        href: "/dashboard/finance",
        icon: <DollarSign size={16} />,
        module: "dashboard_finance",
      },
    ],
  },
  {
    id: "master-data",
    name: "Master Data",
    icon: <Package size={18} />,
    submenu: [
      {
        id: "companies",
        name: "Companies",
        href: "/companies",
        icon: <Factory size={16} />,
        module: "companies",
      },
      {
        id: "branches",
        name: "Branches",
        href: "/branches",
        icon: <Warehouse size={16} />,
        module: "branches",
      },
      {
        id: "categories",
        name: "Categories",
        href: "/categories",
        icon: <Package size={16} />,
        module: "categories",
      },
      {
        id: "sub-categories",
        name: "Sub Categories",
        href: "/sub-categories",
        icon: <Package size={16} />,
        module: "sub_categories",
      },
      {
        id: "metric-units",
        name: "Metric Units",
        href: "/metric-units",
        icon: <Package size={16} />,
        module: "metric_units",
      },
      {
        id: "payment-terms",
        name: "Payment Terms",
        href: "/payment-terms",
        icon: <Package size={16} />,
        module: "payment_terms",
      },
      {
        id: "payment-methods",
        name: "Payment Methods",
        href: "/payment-methods",
        icon: <DollarSign size={16} />,
        module: "payment_methods",
      },
    ],
  },
  {
    id: "products",
    name: "Products",
    icon: <ShoppingCart size={18} />,
    submenu: [
      {
        id: "products",
        name: "Products",
        href: "/products",
        icon: <Package size={16} />,
        module: "products",
      },
      {
        id: "suppliers",
        name: "Suppliers",
        href: "/suppliers",
        icon: <Building2 size={16} />,
        module: "suppliers",
      },
      {
        id: "supplier-products",
        name: "Supplier Products",
        href: "/supplier-products",
        icon: <ShoppingCart size={16} />,
        module: "supplier_products",
      },
      {
        id: "pricelists",
        name: "Pricelists",
        href: "/pricelists",
        icon: <DollarSign size={16} />,
        module: "pricelists",
      },
    ],
  },
  {
    id: "accounting",
    name: "Accounting",
    icon: <Calculator size={18} />,
    submenu: [
      // Core Accounting
      {
        id: "accounting-core",
        name: "Core Accounting",
        icon: <Calculator size={16} />,
        submenu: [
          {
            id: "chart-of-accounts",
            name: "Chart of Accounts",
            href: "/chart-of-accounts",
            icon: <Calculator size={16} />,
            module: "chart_of_accounts",
          },
          {
            id: "accounting-purposes",
            name: "Accounting Purposes",
            href: "/accounting-purposes",
            icon: <Calculator size={16} />,
            module: "accounting_purposes",
          },
          {
            id: "accounting-purpose-accounts",
            name: "Purpose Accounts",
            href: "/accounting-purpose-accounts",
            icon: <Calculator size={16} />,
            module: "accounting_purpose_accounts",
          },
        ],
      },
      // Period & Journals
      {
        id: "accounting-periods",
        name: "Period & Journals",
        icon: <Calculator size={16} />,
        submenu: [
          {
            id: "fiscal-periods",
            name: "Fiscal Periods",
            href: "/accounting/fiscal-periods",
            icon: <Calculator size={16} />,
            module: "fiscal_periods",
          },
          {
            id: "journal-entries",
            name: "Journal Entries",
            href: "/accounting/journals",
            icon: <Calculator size={16} />,
            module: "journals",
          },
          {
            id: "trial-balance",
            name: "Neraca Saldo",
            href: "/accounting/trial-balance",
            icon: <Scale size={16} />,
            module: "journals",  // reuse journals permission
          },
          {
            id: "fee_discrepancy-review",
            name: "Fee Discrepancy Review",
            href: "bank-reconciliation/fee-discrepancy-review",
            icon: <AlertTriangle size={16} />,
            module: "fee_discrepancy_review",
          }
        ],
      },
      // POS Management
      {
        id: "accounting-pos",
        name: "POS Management",
        icon: <FileSpreadsheet size={16} />,
        submenu: [
          {
            id: "pos-imports",
            name: "POS Imports",
            href: "/pos-imports",
            icon: <FileSpreadsheet size={16} />,
            module: "pos_imports",
          },
          {
            id: "pos-staging",
            name: "POS Staging",
            href: "/pos-staging",
            icon: <FileSpreadsheet size={16} />,
            module: "pos_imports",
          },
          {
            id: "pos-transactions",
            name: "POS Transactions",
            href: "/pos-transactions",
            icon: <FileSpreadsheet size={16} />,
            module: "pos_imports",
          },
          {
            id: "pos-sync-aggregates",
            name: "POS Sync Aggregates",
            href: "/pos-sync-aggregates",
            icon: <FileSpreadsheet size={16} />,
            module: "pos_imports",
          },
          {
            id: "pos-aggregates",
            name: "POS Aggregates",
            href: "/pos-aggregates",
            icon: <FileSpreadsheet size={16} />,
            module: "pos_aggregates",
          },
          {
            id: "failed-transactions",
            name: "Failed Transactions",
            href: "/pos-aggregates/failed-transactions",
            icon: <AlertTriangle size={16} />,
            module: "pos_aggregates",
          },
        ],
      },
      // Banking
      {
        id: "accounting-banking",
        name: "Banking",
        icon: <ShieldCheck size={16} />,
        submenu: [
          {
            id: "bank-statement-imports",
            name: "Bank Statement Imports",
            href: "/bank-statement-import",
            icon: <FileSpreadsheet size={16} />,
            module: "bank_statement_imports",
          },
          {
            id: "bank-reconciliation",
            name: "Bank Reconciliation",
            href: "/bank-reconciliation",
            icon: <ShieldCheck size={16} />,
            module: "bank_reconciliation",
          },
          {
            id: "cash-flow",
            name: "Cash Flow",
            href: "/cash-flow",
            icon: <Activity size={16} />,
            module: "cash_flow",
          },
          {
            id: "settlement-groups",
            name: "Settlement Groups",
            href: "/bank-reconciliation/settlement-groups",
            icon: <FileSpreadsheet size={16} />,
            module: "bank_reconciliation",
          },
          {
            id: "cash-counts",
            name: "Cash Count",
            href: "/cash-counts",
            icon: <Coins size={16} />,
            module: "cash_counts",
          },
        ],
      },
    ],
  },
  {
    id: "hr",
    name: "Human Resources",
    icon: <Users size={18} />,
    submenu: [
      {
        id: "employees",
        name: "Employees",
        href: "/employees",
        icon: <Users size={16} />,
        module: "employees",
      },
      {
        id: "employee_branches",
        name: "Employee Branches",
        href: "/employee-branches",
        icon: <Building2 size={16} />,
        module: "employee_branches",
      },
    ],
  },
  {
    id: "settings",
    name: "Settings",
    icon: <Settings size={18} />,
    submenu: [
      {
        id: "users",
        name: "Users",
        href: "/users",
        icon: <UserCog size={16} />,
        module: "users",
      },
      {
        id: "permissions",
        name: "Permissions",
        href: "/permissions",
        icon: <Shield size={16} />,
        module: "permissions",
      },
      {
        id: "monitoring",
        name: "System Monitoring",
        href: "/monitoring",
        icon: <Activity size={16} />,
        module: "monitoring",
      },
    ],
  },
];
