import {
  SaleInput,
  SaleItemInput,
  SalePaymentInput,
} from "./pos-sync.types";

const toDateString = (dateVal: string | null | undefined): string | null => {
  if (!dateVal) return null;
  return dateVal.split(" ")[0]; // ambil "2026-04-05" dari "2026-04-05 14:30:00"
};

export const toSaleRow = (s: SaleInput) => ({
  sales_num: s.salesNum,
  bill_num: s.billNum,
  book_num: s.bookNum,
  queue_num: s.queueNum,
  sales_date: toDateString(s.salesDateIn) ?? s.salesDate, // ← fix: pakai salesDateIn
  sales_date_in: s.salesDateIn,
  order_time_out: s.orderTimeOut,
  sales_date_out: s.salesDateOut,
  branch_id: s.branchID,
  member_id: s.memberID,
  employee_code: s.employeeCode,
  employee_name: s.employeeName,
  employee_type: s.employeeType,
  member_code: s.memberCode,
  table_id: s.tableID,
  visit_purpose_id: s.visitPurposeID,
  visitor_type_id: s.visitorTypeID,
  pax_total: Number(s.paxTotal),
  subtotal: Math.round(Number(s.subtotal ?? 0)), // ← fix
  discount_total: Math.round(Number(s.discountTotal ?? 0)), // ← fix
  menu_discount_total: Math.round(Number(s.menuDiscountTotal ?? 0)),
  promotion_discount: Math.round(Number(s.promotionDiscount ?? 0)),
  voucher_discount_total: Math.round(Number(s.voucherDiscountTotal ?? 0)),
  other_tax_total: Math.round(Number(s.otherTaxTotal ?? 0)), // ← fix
  vat_total: Math.round(Number(s.vatTotal ?? 0)), // ← fix
  other_vat_total: Math.round(Number(s.otherVatTotal ?? 0)),
  delivery_cost: Math.round(Number(s.deliveryCost ?? 0)),
  order_fee: Math.round(Number(s.orderFee ?? 0)),
  grand_total: Math.round(Number(s.grandTotal ?? 0)), // ← fix
  voucher_total: Math.round(Number(s.voucherTotal ?? 0)),
  rounding_total: Math.round(Number(s.roundingTotal ?? 0)),
  payment_total: Math.round(Number(s.paymentTotal ?? 0)),
  billing_print_count: Number(s.billingPrintCount),
  payment_print_count: Number(s.paymentPrintCount),
  additional_info: s.additionalInfo,
  remarks: s.remarks,
  promotion_id: s.promotionID,
  promotion_voucher_code: s.promotionVoucherCode,
  flag_inclusive: s.flagInclusive ? 1 : 0,
  lock_table: s.lockTable ? 1 : 0,
  transaction_mode_id: s.transactionModeID,
  delivery_time: s.deliveryTime,
  external_membership_type_id: s.externalMembershipTypeID,
  flag_external_api: s.flagExternalAPI ? 1 : 0,
  flag_external_member_id: s.flagExternalMemberID,
  flag_external_member_phone: s.flagExternalMemberPhone,
  flag_external_card_id: s.flagExternalCardID,
  external_member_name: s.externalMemberName,
  external_trans_id: s.externalTransID,
  external_cancel_trans_id: s.externalCancelTransID,
  terminal_id: s.terminalID,
  print_eso_fs_qr: s.printEsoFsQr,
  status_id: s.statusID,
  created_by: s.createdBy,
  edited_by: s.editedBy,
  edited_date: s.editedDate,
  sync_date: s.syncDate,
});

export const toSaleItemRow = (i: SaleItemInput) => ({
  // item amounts tidak pecahan, biarkan as-is
  external_id: Number(i.ID),
  local_id: i.localID ?? null,
  sales_num: i.salesNum,
  batch_id: i.batchID,
  menu_ref_id: i.menuRefID,
  menu_group_id: i.menuGroupID,
  menu_id: i.menuID,
  custom_menu_name: i.customMenuName,
  qty: Number(i.qty),
  original_price: Number(i.originalPrice),
  price: Number(i.price),
  inclusive_price: Number(i.inclusivePrice),
  discount: Number(i.discount),
  discount_value: Number(i.discountValue),
  inclusive_discount_value: Number(i.inclusiveDiscountValue),
  other_tax: Number(i.otherTax),
  other_tax_value: Number(i.otherTaxValue),
  vat: Number(i.vat),
  vat_value: Number(i.vatValue),
  other_vat: Number(i.otherVat),
  other_vat_value: Number(i.otherVatValue),
  other_tax_on_vat: Number(i.otherTaxOnVat),
  total: Number(i.total),
  notes: i.notes,
  status_id: i.statusID,
  promotion_detail_id: i.promotionDetailID,
  menu_promotion_id: i.menuPromotionID,
  promotion_voucher_code: i.promotionVoucherCode,
  cancel_notes: i.cancelNotes,
  sales_type: i.salesType,
  flag_pending: Number(i.flagPending),
  created_by: i.createdBy,
  created_date: i.createdDate,
  edited_by: i.editedBy,
  edited_date: i.editedDate,
  sync_date: i.syncDate,
});

export const toSalePaymentRow = (p: SalePaymentInput) => ({
  external_id: Number(p.ID),
  sales_num: p.salesNum,
  local_id: p.localID,
  payment_method_id: p.paymentMethodID,
  voucher_code: p.voucherCode,
  voucher_category_id: p.voucherCategoryID,
  notes: p.notes,
  card_number: p.cardNumber,
  bank_name: p.bankName,
  account_name: p.accountName,
  self_order_id: p.selfOrderID,
  verification_code: p.verificationCode,
  edc_terminal_id: p.edcTerminalID,
  trace_number: p.traceNumber,
  canceled_verification_code: p.canceledVerificationCode,
  flag_external_voucher_api: p.flagExternalVoucherAPI ? 1 : 0,
  external_voucher_code: p.externalVoucherCode,
  external_transaction_id: p.externalTransactionId,
  external_batch_number: p.externalBatchNumber,
  external_canceled_transaction_id: p.externalCanceledTransactionId,
  external_canceled_batch_number: p.externalCanceledBatchNumber,
  coa_no: p.coaNo,
  payment_amount: Math.round(Number(p.paymentAmount ?? 0)), // ← fix
  full_payment_amount: Math.round(Number(p.fullPaymentAmount ?? 0)), // ← fix
  sync_date: p.syncDate,
});
