import { z } from 'zod'

/**
 * Common helpers
 */
const uuidSchema = z.string().uuid()

// ISO date format (YYYY-MM-DD) - DB uses date type, not timestamp
const isoDate = z.string().regex(
  /^\d{4}-\d{2}-\d{2}$/,
  'Date must be in YYYY-MM-DD format'
)

const nullableDate = isoDate.nullable()

/**
 * Enums (aligned with employees.types.ts)
 */
const GenderEnum = z.enum(['Male', 'Female'])
const ReligionEnum = z.enum(['Islam', 'Christian', 'Catholic', 'Hindu', 'Buddha', 'Other'])
const MaritalStatusEnum = z.enum(['Single', 'Married', 'Divorced', 'Widow'])
const StatusEmployeeEnum = z.enum(['Permanent', 'Contract'])
const PTKPStatusEnum = z.enum(['TK/0', 'TK/1', 'TK/2', 'TK/3', 'K/0', 'K/1', 'K/2', 'K/3'])

/**
 * ============================
 * CREATE EMPLOYEE
 * ============================
 */
export const CreateEmployeeSchema = z.object({
  // employee_id OPTIONAL → generated by DB
  employee_id: z.string().max(50).optional(),

  full_name: z.string().min(1).max(255),
  job_position: z.string().min(1).max(100),

  // Required for employee_id generation
  brand_name: z.string().min(1).max(100),
  join_date: isoDate,

  resign_date: nullableDate.optional(),
  sign_date: nullableDate.optional(),
  end_date: nullableDate.optional(),

  status_employee: StatusEmployeeEnum,

  email: z.string().email().optional().nullable(),
  mobile_phone: z.string().max(20).optional().nullable(),
  nik: z.string().max(20).optional().nullable(),

  birth_date: nullableDate.optional(),
  birth_place: z.string().max(255).optional().nullable(),

  gender: GenderEnum.optional().nullable(),
  religion: ReligionEnum.optional().nullable(),
  marital_status: MaritalStatusEnum.optional().nullable(),

  citizen_id_address: z.string().optional().nullable(),

  ptkp_status: PTKPStatusEnum,

  bank_name: z.string().max(100).optional().nullable(),
  bank_account: z.string().max(50).optional().nullable(),
  bank_account_holder: z.string().max(255).optional().nullable(),

  user_id: uuidSchema.optional().nullable(),
  // is_active removed - let DB default to true, only changed via bulk operations
}).superRefine((data, ctx) => {
  // Contract employee must have end_date
  if (data.status_employee === 'Contract' && !data.end_date) {
    ctx.addIssue({
      path: ['end_date'],
      message: 'end_date is required for Contract employee',
      code: z.ZodIssueCode.custom
    })
  }

  // resign_date cannot be before join_date
  if (data.resign_date && data.resign_date < data.join_date) {
    ctx.addIssue({
      path: ['resign_date'],
      message: 'resign_date cannot be before join_date',
      code: z.ZodIssueCode.custom
    })
  }

  // end_date cannot be before join_date
  if (data.end_date && data.end_date < data.join_date) {
    ctx.addIssue({
      path: ['end_date'],
      message: 'end_date cannot be before join_date',
      code: z.ZodIssueCode.custom
    })
  }

  // sign_date cannot be before join_date
  if (data.sign_date && data.sign_date < data.join_date) {
    ctx.addIssue({
      path: ['sign_date'],
      message: 'sign_date cannot be before join_date',
      code: z.ZodIssueCode.custom
    })
  }
})

export type CreateEmployeeInput = z.infer<typeof CreateEmployeeSchema>

/**
 * ============================
 * UPDATE EMPLOYEE
 * ============================
 * - Semua optional
 * - employee_id TIDAK boleh diupdate
 */
export const UpdateEmployeeSchema = CreateEmployeeSchema
  .omit({
    employee_id: true,
    user_id: true,
  })
  .partial()

export type UpdateEmployeeInput = z.infer<typeof UpdateEmployeeSchema>

/**
 * ============================
 * UPDATE PROFILE (SELF)
 * ============================
 */
export const UpdateProfileSchema = z.object({
  full_name: z.string().min(1).max(255).optional(),
  email: z.string().email().optional().nullable(),
  mobile_phone: z.string().max(20).optional().nullable(),
  birth_date: nullableDate.optional(),
  birth_place: z.string().max(255).optional().nullable(),
  gender: GenderEnum.optional().nullable(),
  religion: ReligionEnum.optional().nullable(),
  marital_status: MaritalStatusEnum.optional().nullable(),
  citizen_id_address: z.string().optional().nullable(),
})

export type UpdateProfileInput = z.infer<typeof UpdateProfileSchema>

/**
 * ============================
 * QUERY SCHEMAS
 * ============================
 */
export const EmployeeSearchSchema = z.object({
  q: z.string().min(1),
})

export const EmployeeFilterSchema = z.object({
  branch_name: z.string().optional(),
  job_position: z.string().optional(),
  status_employee: StatusEmployeeEnum.optional(),
  is_active: z.boolean().optional(),
})

export type EmployeeFilterInput = z.infer<typeof EmployeeFilterSchema>

/**
 * ============================
 * BULK OPERATIONS
 * ============================
 */
export const BulkIdSchema = z.object({
  ids: z.array(uuidSchema).min(1),
})

export const BulkUpdateActiveSchema = BulkIdSchema.extend({
  is_active: z.boolean(),
})

export type BulkUpdateActiveInput = z.infer<typeof BulkUpdateActiveSchema>
